# [START app_yaml]
runtime: nodejs
env: flex

# [START env]
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  DB_DATABASE: $DB_DATABASE
  DB_USER: $DB_USER
  DB_PASS: $DB_PASS
  INSTANCE_CONNECTION_NAME: $INSTANCE_CONNECTION_NAME
# [END env]

skip_files:
- .git
- node_modules


# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: utopia-315014:us-west1:utp-dex-db
# [END cloudsql_settings]
# [END app_yaml]